name: Auto Pull Request to Main

on:
  push:
    branches:
      - staging

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create PR to main
        run: |
          gh pr list --state open --head staging --base main --json number | jq length > open_pr_count.txt
          COUNT=$(cat open_pr_count.txt)

          if [ "$COUNT" -eq "0" ]; then
            gh pr create \
              --title "staging → main" \
              --body "Automated PR from staging to main" \
              --base main \
              --head staging
          else
            echo "PR already exists."
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
