name: Auto Pull Request

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Create PR to main
        run: |
          SOURCE_BRANCH=$(echo "${GITHUB_REF#refs/heads/}")
          gh pr list --state open --head "$SOURCE_BRANCH" --base main --json number | jq length > open_pr_count.txt
          COUNT=$(cat open_pr_count.txt)
          
          if [ "$COUNT" -eq "0" ]; then
            gh pr create \
              --title "$SOURCE_BRANCH → main" \
              --body "Automated PR from $SOURCE_BRANCH to main" \
              --base main \
              --head "$SOURCE_BRANCH"
          else
            echo "PR already exists."
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
