name: Lint Code

on:
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Biome
        uses: biomejs/setup-biome@v2.6.0
        with:
          version: latest

      - name: Setup bun
        uses: oven-sh/setup-bun@v2.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 24.2.0

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run linter
        run: bun run lint